steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean','install','-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/spackjava-simple-server', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spackjava-simple-server']
images:
- 'gcr.io/$PROJECT_ID/spackjava-simple-server'
