steps:
###########################################################
# Step 1: Retrieve the cached .m2 directory from GCS
###########################################################
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - 'gs://${_BUCKET}/cache/.m2'
  - '/cache/.m2'
  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'
###########################################################
# Step 2: Build, Test, and Verify
###########################################################
- name: 'gcr.io/cloud-builders/mvn'
  args:
  - 'clean'
  - 'install'
  - '--batch-mode'
  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'
  env:
  - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
###########################################################
# Step 3: Update cached .m2 directory on GCS with any
#         additional dependencies downloaded during the
#         build.
###########################################################
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - '/cache/.m2'
  - 'gs://${_BUCKET}/cache/.m2/'
  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean','install','-Dmaven.test.skip=true']
###########################################################
# Step 4: Build image
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/spackjava-simple-server', '.' ]
###########################################################
# Step 5: Upload image
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spackjava-simple-server']

images:
- 'gcr.io/$PROJECT_ID/spackjava-simple-server'

substitutions:
  # Default values
  _BUCKET: 'maven_cloud_build_m2_cache'
