steps:
###########################################################
# Step 1: Retrieve the cached .m2 directory from GCS
###########################################################
- name: gcr.io/cloud-builders/gsutil
  id: Get M2 Cache
  args: ['cp', 'gs://${_BUCKET}/m2.tar.gz', 'm2.tar.gz']
- name: gcr.io/$PROJECT_ID/tar
  id: Expand M2 Cache
  args: ['tar', 'xpzf', 'm2.tar.gz']
###########################################################
# Step 2: Build, Test, and Verify
###########################################################
- name: 'gcr.io/cloud-builders/mvn'
  id: Test and Build
  args: ['-Dmaven.repo.local=/workspace/.m2/repository', 'clean', 'install', '-Dmaven.test.skip=true']
###########################################################
# Step 3: Update cached .m2 directory on GCS with any
#         additional dependencies downloaded during the
#         build.
###########################################################
- name: gcr.io/$PROJECT_ID/tar
  id: Compress M2 Cache
  args: ['tar','cpzf', 'm2.tar.gz', '.m2']
- name: gcr.io/cloud-builders/gsutil
  id: Save M2 Cache
  args: ['cp', 'm2.tar.gz', 'gs://${_BUCKET}/m2.tar.gz']
###########################################################
# Step 4: Build image
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sparkjava-simple-server', '.' ]
###########################################################
# Step 5: Upload image
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sparkjava-simple-server']

images:
- 'gcr.io/$PROJECT_ID/sparkjava-simple-server'

substitutions:
  # Default values
  _BUCKET: 'maven_cloud_build_m2_cache'
